### ISSUE TITLE
date_picker: Hacer un helper de `DateFormat` para poder borrar la dependencia de `intl`

### ISSUE THREAD

**Issue by Classy-Bear** [Classy-Bear/oshin-list#15]
Al momento se debe usar `DateFormat('YYYY-MM-DD')` para formatear a fecha, esto proviene de un paquete, si se estuviera usando el paquete de manera masiva el uso del paquete fuera válido pero en este caso no lo es.

Leer [formatos de fecha](https://en.wikipedia.org/wiki/Template:Date) para crear el helper, no es necesario cubrir cada caso, es suficiente con _MDY_, _DMY_ y _DMY_.

**Comment by karen-oshin** [comment]
mio

**Comment by karen-oshin** [comment]
listo

**Comment by Classy-Bear** [comment]
Hecho por @karen-oshin
