### ISSUE TITLE
Mejoras en `home_page`...

### ISSUE THREAD

**Issue by Classy-Bear** [Classy-Bear/oshin-list#17]
* Mudar _currentChild a una clase.
* Mejorar la lógica de `onTextChanged`, que primero filtre por el texto que comienza, luego del que termina y luego el de si contiene.

 Por ejemplo:

Si escribo: D

Me tiene que mostrar todos los elemento que comienzan con D, luego que terminan con D y luego que contienen la letra D.

Preferiblemente que al filtrar esto me lo divida por secciones como:

Comienza con:
...
Termina con:
...
Contiene:
...

**Comment by jose-oshin** [comment]
este issue pertenece al taskBloc, espcificamente la metodo getAll
